Repository palantir/gradle-git-version, pull requests merged in 2023-03, with the labels that each got.

#696 ignore user's global gitconfig
  src/test/groovy/com/palantir/gradle/gitversion/GitVersionPluginTests.groovy
  src/test/java/com/palantir/gradle/gitversion/VersionDetailsTest.java
Labels: merge when ready, no changelog

#685 remove jgit
  build.gradle
  changelog/@unreleased/pr-685.v2.yml
  src/main/java/com/palantir/gradle/gitversion/Git.java
  src/main/java/com/palantir/gradle/gitversion/GitDescribe.java
  src/main/java/com/palantir/gradle/gitversion/GitVersionCacheService.java
  src/main/java/com/palantir/gradle/gitversion/JGitDescribe.java
  src/main/java/com/palantir/gradle/gitversion/RefWithTagName.java
  src/main/java/com/palantir/gradle/gitversion/RefWithTagNameComparator.java
  src/main/java/com/palantir/gradle/gitversion/VersionDetailsImpl.java
  src/test/groovy/com/palantir/gradle/gitversion/GitVersionPluginTests.groovy
  src/test/java/com/palantir/gradle/gitversion/VersionDetailsTest.java
  versions.lock
  versions.props
Labels: merge when ready

#705 Issue #704: Use built in git-describe
  changelog/@unreleased/pr-705.v2.yml
  src/main/java/com/palantir/gradle/gitversion/Git.java
  src/main/java/com/palantir/gradle/gitversion/GitUtils.java
  src/main/java/com/palantir/gradle/gitversion/VersionDetailsImpl.java
Labels: merge when ready, autorelease
